### ISSUE TITLE
exception error on new aframe.io version 1.2.0

### ISSUE THREAD

**Issue by killer415tv** [EricEisaman/aframe-trail-component#1]
this error when setting trail attribute to a sphere entity
with version https://aframe.io/releases/1.2.0/aframe.min.js

with version 1.0.4, your trail component works fine

```
core:a-node:error Failure loading node:   TypeError: Cannot read property '0' of undefined
    at o.createTrail (aframe-trail-component.js:69)
    at init (aframe-trail-component.js:174)
    at initComponent (component.js:320)
    at i.updateProperties (component.js:302)
    at HTMLElement.value (a-entity.js:490)
    at HTMLElement.value (a-entity.js:463)
    at a-entity.js:249
    at a-node.js:127
aframe-trail-component.js:124 Uncaught TypeError: Cannot set property 'x' of undefined
    at aframe-trail-component.js:124
    at Array.forEach (<anonymous>)
    at o.updateTrails (aframe-trail-component.js:101)
    at o.tick (aframe-trail-component.js:156)
    at HTMLElement.value (a-scene.js:746)
    at HTMLElement.value (a-scene.js:790)
    at bind.js:12
    at u (three.js:19157)
    at t (three.js:10460)
```

**Comment by Chabloz** [comment]
It's not working with aframe 1.2.0 beacause of this line https://github.com/EricEisaman/aframe-trail-component/blob/master/aframe-trail-component.js#L40
PlaneGeometry is not aviable anymore in the THREE.js version of A-Frame 1.2.0, you should use a PlaneBufferGeometry instead.

**Comment by EricEisaman** [comment]
re: 
It's not working with aframe 1.2.0 beacause of this line https://github.com/EricEisaman/aframe-trail-component/blob/master/aframe-trail-component.js#L40
PlaneGeometry is not aviable anymore in the THREE.js version of A-Frame 1.2.0, you should use a PlaneBufferGeometry instead.

Thanks for the homework Nicolas.  I may have some time today to fix this.

**Comment by Chabloz** [comment]
Replace lines https://github.com/EricEisaman/aframe-trail-component/blob/master/aframe-trail-component.js#L69 and https://github.com/EricEisaman/aframe-trail-component/blob/master/aframe-trail-component.js#L70 
with:

trail.trailVertices[i][0] = trail.mesh.geometry.attributes.position.array[i];
trail.trailVertices[i][1] = trail.mesh.geometry.attributes.position.array[i*2+1];

And it should work with a-frame 1.2.0 :-)
(see https://stackoverflow.com/questions/27198525/three-js-what-is-planebuffergeometry for explanation )

**Comment by EricEisaman** [comment]
@Chabloz Thanks.  Just got pulled into another meeting.  Noticed that I will have to manage the positions a bit differently now that they are array buffer elements rather than vector components.  I will eventually get back to this.  In the meantime PR's are welcome.
https://github.com/EricEisaman/aframe-trail-component/blob/f25f962ee783ec92da8880bdd19597e01488d056/aframe-trail-component.js#L124

**Comment by jameskane05** [comment]
I was able to get as far as Chabloz suggested and get the component to run w/o error, but the trail appears as a large white stationary plane at world origin.

![image](https://user-images.githubusercontent.com/11968217/181925043-b5510162-28b5-4529-84cd-3849df83f316.png)

Any interest in reviving this, @EricEisaman? I will try to take a look at docs and tutorials today but I'm not yet familiar enough w/ how BufferGeometry manages position data. Would love to get this up and running w/ A-Frame 1.3.0 as it would be perfect for my mini-golf game as a ball trail, and it would be a good addition some open source component registries.

**Comment by mrxz** [comment]
I've created a PR that addresses the issue and makes the component compatible with A-Frame 1.3.0. See #2.

It might be a good idea to specify a license for the project. That way people can be certain they can use it in their projects and, in case you would no longer have interesting in maintaining the project, make it easy for people to fork and continue the work :slightly_smiling_face:
